name: Build, Test, and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript
          
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        
      - name: Build frontend Docker image
        run: |
          docker build -t chat-frontend ./public

      - name: Build backend Docker image
        run: |
          docker build -t chat-backend ./server

      - name: Run security scan on frontend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: chat-frontend

      - name: Run security scan on backend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: chat-backend

      - name: Tag and push frontend Docker image
        run: |
          docker tag chat-frontend ${{ secrets.DOCKERHUB_USERNAME }}/chat-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-frontend:latest

      - name: Tag and push backend Docker image
        run: |
          docker tag chat-backend ${{ secrets.DOCKERHUB_USERNAME }}/chat-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-backend:latest
